language: erlang
matrix:
  include:
    - os: linux
      otp_release: 17.5
    - os: linux
      otp_release: 18.3
    - os: linux
      otp_release: 19.3
    - os: linux
      otp_release: 20.0
    - os: linux
      otp_release: 21.0
    - os: osx
      language: generic
      
